
default: &default
  adapter: postgresql
  encoding: unicode
 
  pool: 5

development:
  <<: *default
  database: dyno_app_development




test:
  <<: *default
  database: dyno_app_test


production:
  <<: *default
  database: dyno_app_production
  username: dyno_app
  password: <%= ENV['DYNO_APP_DATABASE_PASSWORD'] %>
