# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4a61a10fe715b116f607d1bcc701a5388b1486521e0ee2550c3e48ef3943368be5d5c0883711b8d33eecdd3b62d2aaeb4fd5566f1d9d906b4f26c97146e6d0e8

test:
  secret_key_base: 94a241af14ca76de2b6d0b765289fc04700267f1a130e8b7dcc9956bda90903cce189e52cb2d0da801e379e3dc3f149800f8a2d135b7a987a78fa74bcdf8be82

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
