

var dinoArray =
["Abelisaurus comahuensi",
"Abrictosaurus consors",
"Acanthopholis eucercus",
"Acanthopholis horridus",
"Acanthopholis macrocercus",
"Acanthopholis platypus",
"Acanthopholis stereocercus",
"Achelousaurus horneri",
"Acrocanthosaurus altispinax",
"Acrocanthosaurus atokensis",
"Adasaurus mongoliensis",
"Aegyptosaurus baharijensis",
"Aelosaurus rionegrinus",
"Aepysaurus elephantinus",
"Aetonyx palustris",
"Agathaumas milo",
"Agathaumas sylvestris",
"Agilisaurus louderbacki",
"Agilisaurus multidens",
"Agrosaurus macgillivrayi",
"Alamosaurus sanjuanensis",
"Albertosaurus arctunguis",
"Albertosaurus libratus",
"Albertosaurus megagracilis",
"Albertosaurus periculosus",
"Albertosaurus sarcophagus",
"Albisaurus scutifer",
"Alectrosaurus olseni",
"Algoasaurus bauri",
"Alioramus remotus",
"Aliwalia rex",
"Allosaurus ferox ",
"Allosaurus fragilis",
"Allosaurus lucaris ",
"Allosaurus medius",
"Allosaurus sibiricus",
"Allosaurus tendagurensis",
"Alocodon kuehnei",
"Altispinax dunkeri",
"Alvarezsaurus calvoi",
"Alxasaurus elesitaiensis",
"Amargasaurus cazaui",
"Ammosaurus major",
"Ampelosaurus atacis",
"Amphicoelias altus",
"Amphicoelias fragillimus",
"Amphicoelias latus ",
"Amtosaurus magnus ",
"Amygdalodon",
"patagonicus",
"Anasazisaurus horneri",
"Anatosaurus copei",
"Anatotitan copei",
"Anchiceratops longirostris",
"Anchiceratops ornatus",
"Anchisaurus colurus",
"Anchisaurus major",
"Anchisaurus polyzelus",
"Anchisaurus solus",
"Andesaurus delgadoi",
"Angaturama limai",
"Ankylosaurus magniventris",
"Anodontosaurus lambei",
"Anoplosaurus curtonotus",
"Anoplosaurus major",
"Anserimimus planinychus",
"Antarctosaurus brasiliensis",
"Antarctosaurus giganteus",
"Antarctosaurus jaxartensis",
"Antarctosaurus septentrionalis",
"Antarctosaurus wichmannianus",
"Anthodon serrarius",
"Apatosaurus ajax",
"Apatosaurus alenquerensis",
"Apatosaurus grandis",
"Apatosaurus laticollis",
"Apatosaurus louisae",
"Apatosaurus minimus",
"Apatosaurus yahnahpin",
"Aragosaurus ischiaticus",
"Aralosaurus tuberiferus",
"Archaeornithoides deinosauriscus",
"Archaeornithomimus asiaticus",
"Arctosaurus osborni",
"Argentinosaurus huinculensis",
"Argyrosaurus superbus",
"Aristosaurus erectus",
"Arrhinoceratops brachyops",
"Arrhinoceratops utahensis",
"Arstanosaurus akkurganensis",
"Asiaceratops salsopaludalis",
"Asiatosaurus kwangshiensis",
"Asiatosaurus mongoliensis",
"Astrodon johnstoni",
"Astrodon pusillus",
"Atlantosaurus excelcus",
"Atlantosaurus immanis",
"Atlascopcosaurus loadsi",
"Aublysodon amplus",
"Aublysodon cristatus",
"Aublysodon lateralis",
"Aublysodon mirandus",
"Aublysodon molnari",
"Austrosaurus mckillopi",
"Avaceratops lammersi",
"Avimimus portentosus",
"Avipes dillstedtianus",
"Avisaurus archibaldi",
"Avalonianus sanfordi",
"Azendohsauru laaroussii",
"Anthodon serrarius",
"Apatosaurus ajax",
"Apatosaurus alenquerensis",
"Apatosaurus grandis",
"Apatosaurus laticollis",
"Apatosaurus louisae",
"Apatosaurus minimus",
"Apatosaurus yahnahpin",
"Aragosaurus ischiaticus",
"Aralosaurus tuberiferus",
"Archaeornithoides deinosauriscus",
"Archaeornithomimus asiaticus",
"Arctosaurus osborni",
"Argentinosaurus huinculensis",
"Argyrosaurus superbus",
"Aristosaurus erectus",
"Arrhinoceratops brachyops",
"Arrhinoceratops utahensis",
"Arstanosaurus akkurganensis",
"Asiaceratops salsopaludalis",
"Asiatosaurus kwangshiensis",
"Asiatosaurus mongoliensis",
"Astrodon johnstoni",
"Astrodon pusillus",
"Atlantosaurus excelcus",
"Atlantosaurus immanis",
"Atlascopcosaurus loadsi",
"Aublysodon amplus",
"Aublysodon cristatus",
"Aublysodon lateralis",
"Aublysodon mirandus",
"Aublysodon molnari",
"Austrosaurus mckillopi",
"Avaceratops lammersi",
"Avimimus portentosus",
"Avipes dillstedtianus",
"Avisaurus archibaldi",
"Avalonianus sanfordi",
"Azendohsaurus laaroussii",
"Bactrosaurus johnsoni",
"Bactrosaurus prynadai",
"Bagaceratops rozhdestvenskyi",
"Bahariasaurus ingens",
"Barapasaurus tagorei",
"Barosaurus affinis",
"Barosaurus africanus",
"Barosaurus gracilis",
"Barosaurus lentus",
"Barsboldia sicinskii",
"Baryonyx walkeri",
"Basutodon ferox",
"Becklespinax altispinax",
"Bellusaurus sui",
"Bison alticornis",
"Blikanasaurus cromptoni",
"Borogovia gracilicrus",
"Bothriospondylus elongatus",
"Bothriospondylus madagascariensis",
"Bothriospondylus magnus",
"Bothriospondylus robustus",
"Bothriospondylus suffosus",
"Brachiosaurus altithorax",
"Brachiosaurus atalaiensis",
"Brachiosaurus brancai",
"Brachiosaurus fraasi",
"Brachiosaurus nougaredi",
"Brachyceratops montanensis",
"Brachylophosaurus canadensis",
"Brachylophosaurus goodwini",
"Brachypodosaurus gravis",
"Brachyrophus altarkansanus",
"Bradycneme draculae",
"Breviceratops kozlowskii",
"Brontosaurus amplus",
"Brontosaurus excelsus",
"Bugenasaura infernalis",
"Caenagnathasia martinsoni",
"Caenagnathus collinsi",
"Caenagnathus sternbergi",
"Calamospondylus foxi",
"Calamospondylus oweni",
"Camarasaurus alenquerensis",
"Camarasaurus annae",
"Camarasaurus grandis",
"Camarasaurus ischiaticus",
"Camarasaurus lentus",
"Camarasaurus lewisi",
"Camarasaurus leptodirus",
"Camarasaurus supremus",
"Camelotia borealis",
"Camplodoniscus ameghinoi",
"Camptonotus amplus",
"Camptonotus dispar",
"Camptosaurus amplus",
"Camptosaurus browni",
"Camptosaurus depressus",
"Camptosaurus dispar",
"Camptosaurus inkeyi",
"Camptosaurus leedsi",
"Camptosaurus medius",
"Camptosaurus nanus",
"Camptosaurus prestwichii",
"Camptosaurus valdensis",
"Campylodon ameghinoi",
"Carcharodontosaurus saharicus",
"Cardiodon rugulosus",
"Carnotaurus sastrei",
"Cathetosaurus lewisi",
"Caulodon diversidens",
"Caulodon leptoganus",
"Centrosaurus apertus",
"Centrosaurus longirostris",
"Ceratops horridus",
"Ceratops montanus",
"Ceratosaurus nasicornis",
"Ceratosaurus roechlingi",
"Cetiosauriscus glymptonensis",
"Cetiosauriscus longus",
"Cetiosauriscus stewarti",
"Cetiosaurus brevis",
"Cetiosaurus conybeari",
"Cetiosaurus epioolithicus",
"Cetiosaurus giganteus",
"Cetiosaurus glymptonensis",
"Cetiosaurus greppini",
"Cetiosaurus humerocristatus",
"Cetiosaurus hypoolithicus",
"Cetiosaurus longus",
"Cetiosaurus medius",
"Cetiosaurus mogrebiensis",
"Cetiosaurus oxoniensis",
"Chasmosaurus belli",
"Chasmosaurus brevirostris",
"Chasmosaurus canadensis",
"Chasmosaurus",
"Chasmosaurusmariscalensis ",
"Cheneosaurus russelli",
"Chialingosaurus kuani",
"Chialingosaurus Chialingosaurus",
"Chiayusaurus lacustris",
"Chienkosaurus ceratosauroides",
"Chilantaisaurus maortuensis",
"Chilantaisaurus sibiricus",
"Chilantaisaurus tashuikouensis",
"Chilantaisaurus zheziangensis",
"Chindesaurus bryansmalli",
"Chingkankousaurus fragilis",
"Chirostenotes pergracilis",
"Chonchoraptor gracilis ",
"Chondrosteosaurus gigas",
"Chuandongocoelurus primitivus",
"Chubutisaurus insignis ",
"Chungkingosaurus jiangbeiensis",
"Cionodon arctatus",
"Cionodon kysylkumensis",
"Cionodon stenopsis",
"Claorhynchus trihedrus",
"Claosaurus affinis",
"Claosaurus agilis",
"Claosaurus annectens",
"Clasmodosaurus spatula",
"Clepsisaurus fraserianus",
"Coelophysis bauri",
"Coelosaurus affinis",
"Coelosaurus antiquus",
"Coeluroides largus",
"Coelurus agilis",
"Coelurus bauri",
"Coelurus fragilis",
"Coelurus gracilis",
"Coelurus longicollis",
"Coloradia brevis",
"Coloradisaurus brevis",
"Compsognathus corallestris",
"Compsognathus longipes",
"Compsosuchus solus ",
"Corythosaurus bicristatus",
"Corythosaurus brevicristatus",
"Corythosaurus casuarius",
"Corythosaurus excavatus",
"Corythosaurus frontalis",
"Corythosaurus intermedius",
"Craspedodon lonzeensis",
"Crataeomus lepidophorus",
"Crataeomus pawlowitschii",
"Craterosaurus pottonensis",
"Creosaurus atrox",
"Creosaurus potens",
"Cryptosaurus eumerus",
"Dacentrurus armatus",
"Danubiosaurus anceps",
"Daspletosaurus torosus",
"Datousaurus bashanensis",
"Deinocheirus mirificus",
"Deinodon horridus",
"Deinonychus antirrhopus",
"Denversaurus schlessmani",
"Dianchungosaurus lufengensis",
"Diclonius calamarius",
"Diclonius pentagonus",
"Diclonius perangulatus",
"Dicraeosaurus hansemanni",
"Dicraeosaurus sattleri",
"Dilophosaurus sinensis",
"Dilophosaurus wetherilli",
"Dimodosaurus poligniensis",
"Dinodocus mackesoni",
"Dinosaurus gresslyi",
"Diplodocus carnegii",
"Diplodocus hayi",
"Diplodocus lacustris",
"Diplodocus longus",
"Diracodon laticeps",
"Dolichosuchus cristatus",
"Dracopelta zbyszewskii",
"Dravidosaurus blanfordi",
"Drinker nisti",
"Dromaeosaurus albertensis",
"Dromiceiomimus brevitertius",
"Dromiceiomimus samueli",
"Dromicosaurus gracilis",
"Dryosaurus altus ",
"Dryosaurus canaliculatus ",
"Dryosaurus lettowvorbecki",
"Dryptosauroides grandis",
"Dryptosaurus aquilunguis",
"Dryptosaurus gallicus ",
"Dryptosaurus kenabekides",
"Dynamosaurus imperiosus",
"Dyoplosaurus acutosquameus",
"Dyoplosaurus giganteus ",
"Dysalotosaurus lettow-vorbecki",
"Dysganus bicarinatus",
"Dysganus encaustus",
"Dysganus haydenianus ",
"Dysganus peiganus",
"Dyslocosaurus polyonychius",
"Dystrophaeus viaemalae  ",
"Dystylosaurus edwini",
"Echinodon becklesii",
"Edmarka rex",
"Edmontonia longiceps",
"Edmontonia rugosidens",
"Edmontosaurus annectens",
"Edmontosaurus regalis",
"Edmontosaurus saskatchewanensis",
"Einiosaurus procurvicornis",
"Elaphrosaurus bambergi",
"Elaphrosaurus gautieri",
"Elaphrosaurus iguidiensis",
"Elmisaurus elegans",
"Elmisaurus rarus",
"Elopteryx nopcsai",
"Elosaurus parvus",
"Emausaurus ernsti",
"Embasaurus minax",
"Enigmosaurus mongoliensis",
"Eoceratops canadensis",
"Eoraptor lunensis",
"Epachthosaurus sciuttoi",
"Epanterias amplexus",
"Erectopus sauvagei",
"Erectopus superbus",
"Erlikosaurus andrewsi",
"Eucamerotus foxi",
"Eucercosaurus tanyspondylus",
"Eucnemesaurus fortis",
"Euhelopus zdanskyi",
"Euoplocephalus tutus",
"Euronychodon portucalensis",
"Euskelosaurus africanus",
"Euskelosaurus browni",
"Eustreptospondylus divesensis",
"Eustreptospondylus oxoniensis",
"Fabrosaurus australis",
"Frenguellisaurus ischigualastensis",
"Fulengia youngi",
"Fulgurotherium australe",
"Gallimimus bullatus",
"Garudimimus brevipes",
"Gasosaurus constructus",
"Gasparinisaura cincosaltensis",
"Genusaurus sisteronis",
"Genyodectes serus",
"Geranosaurus atavus",
"Gigantosaurus africanus",
"Giganotosaurus carolinii",
"Gigantosaurus dixeyi",
"Gigantosaurus megalonyx",
"Gigantosaurus robustus",
"Gigantoscelus molengraaffi",
"Gilmoreosaurus mongoliensis",
"Giraffotitan altithorax",
"Gongbusaurus shiyii",
"Gongbusaurus wucaiwanensis",
"Gorgosaurus lancensis",
"Gorgosaurus lancinator",
"Gorgosaurus libratus",
"Gorgosaurus novojilovi",
"Gorgosaurus sternbergi",
"Goyocephale lattimorei",
"Gravitholus albertae",
"Gresslyosaurus ingens",
"Gresslyosaurus robustus",
"Gresslyosaurus torgeri",
"Gryponyx africanus",
"Gryponyx taylori",
"Gryponyx transvaalensis",
"Gryposaurus notabilis",
"Gryposaurus latidens",
"Gyposaurus capensis",
"Gyposaurus sinensis",
"Hadrosaurus agilis",
"Hadrosaurus breviceps",
"Hadrosaurus cavatus",
"Hadrosaurus foulkii",
"Hadrosaurus minor",
"Hadrosaurus notabilis",
"Hadrosaurus paucidens",
"Halticosaurus liliensternus",
"Halticosaurus longotarsus",
"Halticosaurus orbitoangulatus",
"Haplocanthosaurus delfsi",
"Haplocanthosaurus priscus",
"Haplocanthosaurus utterbacki",
"Harpymimus okladnikovi",
"Heishansaurus pachycephalus",
"Helopus zdanskyi",
"Heptasteornis andrewsi",
"Herrerasaurus ischigualastensis",
"Heterodontosaurus tucki",
"Heterosaurus neocomiensis",
"Hierosaurus coleii",
"Hierosaurus sternbergi",
"Homalocephale calathocercos",
"Hoplitosaurus marshi",
"Hoplosaurus ischyrus",
"Hortalotarsus skirtopodus",
"Huayangosaurus taibaii",
"Hulsanpes perlei",
"Hylaeosaurus armatus",
"Hylaeosaurus oweni",
"Hylosaurus mantelli",
"Hypacrosaurus altispinus",
"Hypacrosaurus stebingeri",
"Hypselosaurus priscus",
"Hypsibema crassicauda",
"Hypsilophodon foxii",
"Hypsilophodon wielandi",
"Hypsirhophus discurus",
"Hypsirophus seeleyanus",
"Iguanodon anglicus",
"Iguanodon atherfieldensis ",
"Iguanodon bernissartensis ",
"Iguanodon dawsoni",
"Iguanodon exogirarus",
"Iguanodon fittoni",
"Iguanodon hilli",
"Iguanodon hoggi",
"Iguanodon hollingtoniensis",
"Iguanodon lakotaensis",
"Iguanodon mantelli",
"Iguanodon orientalis",
"Iguanodon ottingeri",
"Iguanodon phillipsii",
"Iguanodon praecursor",
"Iguanodon prestwichii",
"Iguanodon seeleyi",
"Iguanodon suessi",
"Iliosuchus incognitus",
"Indosaurus matleyi",
"Indosuchus raptorius",
"Ingenia yanshini",
"Inosaurus tedreftensis",
"Irritator challengeri",
"Ischisaurus cattoi",
"Ischyrosaurus manseli",
"Itemirus medullaris",
"Janenschia robusta",
"Jaxartosaurus aralensis",
"Jaxartosaurus fuyunensis",
"Jubbulpuria tenuis",
"Kaijiangosaurus lini",
"Kakuru kujani",
"Kangnasaurus coetzeei",
"Kelmayisaurus petrolicus",
"Kentrosaurus aethiopicus",
"Kentrurosaurus aethiopicus",
"Klamelisaurus gobiensis",
"Koparion douglassi",
"Kotasaurus yamanpalliensis",
"Kritosaurus australis",
"Kritosaurus horneri",
"Kritosaurus incurvimanus",
"Kritosaurus navajovius",
"Labocania anomala",
"Labrosaurus ferox",
"Labrosaurus stechowi",
"Labrosaurus sulcatus",
"Laelaps aquilunguis",
"Laelaps cristatus",
"Laelaps explanatus",
"Laelaps falculus",
"Laelaps gallicus",
"Laelaps hazenianus",
"Laelaps incrassatus",
"Laelaps laevifrons",
"Laelaps macropus",
"Laelaps trihedrodon",
"Laevisuchus indicus",
"Lambeosaurus clavinitialis",
"Lambeosaurus lambei",
"Lambeosaurus laticaudus",
"Lambeosaurus magnicristatus",
"Lametasaurus indicus",
"Lametasaurus indicus",
"Lanasaurus scalpridens",
"Laosaurus altus",
"Laosaurus celer",
"Laosaurus consors",
"Laosaurus gracilis",
"Laosaurus minimus",
"Laplatasaurus araukanicus",
"Lapparentosaurus madagascariensis",
"Leaellynasaura amicagraphica",
"Leipsanosaurus noricus",
"Leptoceratops cerorhynchus",
"Leptoceratops gracilis",
"Leptospondylus capensis",
"Lesothosaurus diagnosticus",
"Lexovisaurus durobrivensis",
"Liliensternus airelensis",
"Liliensternus lilliensterni",
"Limnosaurus transsylvanicus",
"Lisboasaurus estesi",
"Loncosaurus argentinus",
"Longosaurus longicollis",
"Lophorhothon atopus",
"Loricosaurus scutatus",
"Lucianosaurus wildi",
"Lufengosaurus huenei",
"Lufengosaurus magnus",
"Lukousaurus yini",
"Lusitanosaurus liassicus",
"Lycorhinus angustidens",
"Lycorhinus consors",
"Macrophalangia canadensis",
"Macrurosaurus semnus",
"Magnosaurus nethercombensis",
"Magyarosaurus dacus",
"Magyarosaurus hungaricus",
"Magyarosaurus transsylvanicu",
"Maiasaura peeblesorum",
"Majungasaurus crenatissimus",
"Majungatholus atopus",
"Maleevus disparoserratus",
"Mamenchisaurus constructus",
"Mamenchisaurus hochuanensis",
"Mamenchisaurus jingyanensis",
"Mamenchisaurus sinocanadorum",
"Mandschurosaurus laosensis",
"Mandschurosaurus mongoliensis",
"Manospondylus gigas",
"Marmarospondylus robustus",
"Marshosaurus bicentesimus",
"Massospondylus browni",
"Massospondylus carinatus",
"Massospondylus harriesi",
"Massospondylus hislopi",
"Massospondylus rawsei",
"Massospondylus schwarzi",
"Megadactylus polyzelus",
"Megalosaurus africanus",
"Megalosaurus bradleyi",
"Megalosaurus bredai",
"Megalosaurus bucklandii",
"Megalosaurus cambrensis",
"Megalosaurus chubutensis",
"Megalosaurus cloacinus",
"Megalosaurus crenatissimus",
"Megalosaurus dunkeri",
"Megalosaurus hesperis",
"Megalosaurus hungaricus",
"Megalosaurus ingens",
"Megalosaurus inexpectatus",
"Megalosaurus insignis",
"Megalosaurus lonzeensis",
"Megalosaurus lydekkeri",
"Megalosaurus meriani",
"Megalosaurus nethercombensis",
"Megalosaurus obtusus",
"Megalosaurus oweni",
"Megalosaurus pannoniensis",
"Megalosaurus parkeri",
"Megalosaurus pombali",
"Megalosaurus saharicus",
"Megalosaurus superbus",
"Megalosaurus terquemi",
"Megalosaurus wetherilli",
"Melanorosaurus readi",
"Melanorosaurus thabanensi",
"Metriacanthosaurus parkeri",
"Microceratops gobiensis",
"Microceratops sulcidens",
"Microcoelus australis",
"Microcoelus patagonicus",
"Microhadrosaurus nanshiungensis",
"Micropachycephalosaurus hongtuyanensis",
"Microvenator celer",
"Minmi paravertebra",
"Mochlodon robustus",
"Mongolosaurus haplodon",
"Monkonosaurus lawulacus",
"Monoclonius belli",
"Monoclonius canadensis",
"Monoclonius crassus",
"Monoclonius cutleri",
"Monoclonius dawsoni",
"Monoclonius fissus",
"Monoclonius flexus",
"Monoclonius lowei",
"Monoclonius nasicornus",
"Monoclonius recurvicornis",
"Monoclonius sphenocerus",
"Monolophosaurus jiangi",
"Montanoceratops cerorhynchus",
"Morinosaurus typus",
"Morosaurus agilis",
"Morosaurus impar",
"Morosaurus lentus",
"Morosaurus robustus",
"Mussaurus patagonicus",
"Muttaburrasaurus langdoni",
"Mymoorapelta maysi",
"Naashoibitosaurus",
"Nanningosaurus",
"Nanosaurus",
"Nanotyrannus",
"Nanshiungosaurus",
"Nanyangosaurus",
"Nectosaurus",
"Nedcolbertia",
"Nedoceratops",
"Neimongosaurus",
"Nemegtia",
"Nemegtomaia",
"Nemegtomai",
"Nemegtosaurus",
"Neosaurus",
"Neosodon",
"Neovenator",
"Neuquenraptor",
"Neuquensaurus",
"Newtonsaurus",
"Nigersaurus",
"Niobrarasaurus",
"Nipponosaurus",
"Noasaurus",
"Nodocephalosaurus",
"Nodosaurus",
"Nomingia",
"Nopcsaspondylus",
"Nothronychus",
"Notoceratops",
"Notohypsilophodon",
"Nqwebasaurus",
"Nuthetes",
"Nyasasaurus",
"Nyororosaurus",
"Ohmdenosaurus",
"Oligosaurus",
"Olorotitan",
"Omeisaurus",
"Omnivoropteryx",
"Omosaurus",
"Onychosaurus",
"Opisthocoelicaudia",
"Oplosaurus",
"Orinosaurus",
"Orkoraptor",
"Ornatotholus",
"Ornithodesmus",
"Ornitholestes",
"Ornithomerus",
"Ornithomimoides",
"Ornithomimus",
"Ornithopsis",
"Ornithosuchus",
"Ornithotarsus",
"Orodromeus",
"Orosaurus",
"Orthogoniosaurus",
"Orthomerus",
"Oryctodromeu",
"Othnielia",
"Othnielosaurus",
"Ouranosaurus",
"Oviraptor",
"Ozraptor",
"Pachycephalosaurus",
"Pachyrhinosaurus",
"Pachysauriscus",
"Pachysaurops",
"Pachysaurus",
"Pachyspondylus",
"Pakisaurus",
"Palaeoctonus",
"Palaeocursornis",
"Palaeopteryx",
"Palaeosauriscus",
"Palaeosaurus",
"Palaeoscincus",
"Paluxysaurus",
"Panoplosaurus",
"Panphagia",
"Pantydraco",
"Paraiguanodon",
"Paralititan",
"Paranthodon",
"Pararhabdodon",
"Parasaurolophus",
"Pareiasaurus",
"Parksosaurus",
"Paronychodon",
"Parrosaurus",
"Parvicursor",
"Patagonykus",
"Patagosaurus",
"Pawpawsaurus",
"Pectinodon",
"Pedopenna",
"Peishansaurus",
"Pekinosaurus",
"Pelecanimimus",
"Pellegrinisaurus",
"Peloroplites",
"Pelorosaurus",
"Penelopognathus",
"Pentaceratops",
"Phaedrolosaurus",
"Phuwiangosaurus",
"Phyllodon",
"Piatnitzkysaurus",
"Picrodon",
"Pinacosaurus",
"Pisanosaurus",
"Pitekunsaurus",
"Piveteausaurus",
"Planicoxa",
"Plateosauravus",
"Plateosaurus",
"Platyceratops",
"Pleurocoelus",
"Pleuropeltus",
"Pneumatoarthrus ",
"Podokesaurus",
"Poekilopleuron",
"Polacanthoides",
"Polacanthus",
"Polyodontosaurus",
"Polyonax",
"Ponerosteus",
"Poposaurus",
"Postosuchus",
"Pradhania",
"Prenocephale",
"Prenoceratops",
"Priconodon",
"Priodontognathus",
"Probactrosaurus",
"Proceratops",
"Proceratosaurus",
"Procerosaurus",
"Procheneosaurus",
"Procompsognathus",
"Prodeinodon",
"Prosaurolophus",
"Protarchaeopteryx",
"Protecovasaurus",
"Protiguanodon",
"Protoavis",
"Protoceratops",
"Protognathosaurus",
"Protohadros",
"Protorosaurus",
"Pseudolagosuchus",
"Psittacosaurus",
"Pteropelyx",
"Pterospondylus",
"Puertasaurus",
"Pukyongosaurus",
"Pycnonemosaurus",
"Pyroraptor",
"Qantassaurus",
"Qiaowanlong",
"Qinlingosaurus",
"Qingxiusaurus",
"Quaesitosaurus",
"Quilmesaurus",
"Rachitrema",
"Rahonavis",
"Rajasaurus",
"Rapator",
"Rapetosaurus",
"Raptorex",
"Rayososaurus",
"Razanandrongobe",
"Rebbachisaurus",
"Regnosaurus",
"Revueltosaurus",
"Rhabdodon",
"Rhadinosaurus",
"Rhodanosaurus",
"Rhoetosaurus",
"Rhopalodon",
"Ricardoestesia",
"Richardoestesia",
"Rileyasuchus",
"Rinchenia",
"Rinconsaurus",
"Rioarribasaurus",
"Riojasaurus",
"Riojasuchus",
"Rocasaurus",
"Ruehleia",
"Rugops",
"Ruyangosaurus",
"Sacisaurus",
"Sahaliyania",
"Saichania",
"Saltasaurus",
"Saltopus",
"Sanpasaurus",
"Santanaraptor",
"Sarcolestes",
"Sarcosaurus",
"Saturnalia",
"Sauraechinodon",
"Saurolophus",
"Sauropelta",
"Saurophaganax",
"Sauroplites",
"Sauroposeidon",
"Saurornithoides",
"Saurornitholestes",
"Scansoriopteryx",
"Scaphonyx",
"Scelidosaurus",
"Scipionyx",
"Scleromochlus",
"Scolosaurus",
"Scutellosaurus",
"Secernosaurus",
"Segisaurus",
"Segnosaurus",
"Seismosaurus",
"Sellosaurus",
"Serendipaceratops",
"Shamosaurus",
"Shanag",
"Shanshanosaurus",
"Shantungosaurus",
"Shanxia",
"Shanyangosaurus",
"Shaochilong",
"Shenzhousaurus",
"Shidaisaurus",
"Shixinggia",
"Shuangmiaosaurus",
"Shunosaurus",
"Shuvosaurus",
"Shuvuuia",
"Siamosaurus",
"Siamotyrannus",
"Sigilmassasaurus",
"Silesaurus",
"Siluosaurus",
"Silvisaurus",
"Similicaudipteryx",
"Sinocalliopteryx",
"Sinocoelurus",
"Sinornithoides",
"Sinornithomimus",
"Sinornithosaurus",
"Sinosauropteryx",
"Sinosaurus",
"Sinovenator",
"Sinraptor",
"Sinucerasaurus",
"Sinusonasus",
"Skorpiovenator",
"Sonidosaurus",
"Sonorasaurus",
"Sphaerotholus",
"Sphenosaurus",
"Sphenospondylus",
"Spinophorosaurus",
"Spinosaurus",
"Spinostropheus",
"Spinosuchus",
"Spondylosoma",
"Squalodon",
"Staurikosaurus",
"Stegoceras",
"Stegopelta",
"Stegosaurides",
"Stegosaurus",
"Stenonychosaurus",
"Stenopelix",
"Stenotholus",
"Stephanosaurus",
"Sterrholophus",
"Stokesosaurus",
"Stormbergia",
"Strenusaurus",
"Streptospondylus",
"Struthiomimus",
"Struthiosaurus",
"Stygimoloch",
"Stygivenator",
"Styracosaurus",
"Suchomimus",
"Suchosaurus",
"Suchoprion",
"Sulaimanisaurus",
"Supersaurus",
"Suuwassea",
"Suzhousaurus",
"Symphyrophus",
"Syngonosaurus",
"Syrmosaurus",
"Szechuanosaurus",
"Tarbosaurus",
"Tetrapod",
"Thecodontosaurus",
"Therizinosaurus",
"Thyreophora",
"Titanosaurids",
"Torvosaurus",
"Triceratops",
"Troodon",
"Tyrannosaurus rex",
"Ultrasauros",
"Unaysaurus",
"Utahraptor",
"Unenlagia",
"Unescoceratops",
"Velociraptor",
"Valdosaurus",
"Velafrons",
"Venenosaurus",
"Veterupristisaurus",
"Vitakridrinda ",
"Vulcanodon",
"Walgettosuchus",
"Wannanosaurus",
"Wulagasaurus",
"Xenoceratops",
"Xenotarsosaurus",
"Xixianykus",
"Xuanhanosaurus",
"Xuanhuaceratops",
"Yangchuanosaurus",
"Yandusaurus",
"Yunnanosaurus",
"Yimenosaurus",
"Yutyrannus",
"Yixianosaurus",
"Yongjinglong",
"Yueosaurus",
"Zalmoxes ",
"Zhuchengtyrannus",
"Zephyrosaurus ",
"Zuniceratops",
"Zhanghenglong",
"Zhejiangosaurus",
"Zizhongosaurus",
"Zhuchengceratops"];
 
getRandom = function (dinoArray) {
  	return dinoArray[Math.floor((Math.random()*dinoArray.length))];
}

getRandom(dinoArray);


